# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Willem Handreck
name: Willem Handreck
email: hi@willemhandreck.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! Welcome to my blog. I believe building things that work alongside
  humanity and not against it is one of the most important things we can be
  doing. I'm getting better at what I do so I can help make life better for
  everyone.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:title
url: https://willem-h.github.io # the base hostname & protocol for your site
github_username: willem-h

# Build settings
markdown: kramdown

gems:
  - jemoji
